apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      track: stable
  template:
    metadata:
      labels:
        app: backend
        track: stable
        version: 1.0.0
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: backend
          image: f73-g2.cloudogu.net/achilles/backend:2.5
          ports:
          - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /adl-api/v1/ready
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /adl-api/v1/alive
              port: 8080
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-map
                  key: host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-map
                  key: port
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: backend-map
                  key: database