apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      track: stable
  template:
    metadata:
      labels:
        app: frontend
        track: stable
        version: 1.0.0
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: frontend
          image: f73-g2.cloudogu.net/achilles/frontend:1.3
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            initialDelaySeconds: 20
            httpGet:
              path: /
              port: 80