apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      track: stable
  template:
    metadata:
      labels:
        app: frontend
        track: stable
        version: 1.0.0
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: frontend
          image: f73-g2.cloudogu.net/achilles/frontend:1.1
          ports:
          - containerPort: 4200