apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: recorder
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: recorder
            image: f73-g2.cloudogu.net/achilles/recorder:1.5
            env:
            - name: URL
              value: backend
            - name: PORT
              value: "8080"
          imagePullSecrets:
          - name: regcred
          restartPolicy: OnFailure