apiVersion: v1
kind: PersistentVolume
metadata:
  name: recorder-volume
  labels:
    type: local
spec:
  storageClassName: recorder
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/stateful_partition/data"